### ISSUE TITLE
Does this part worth the attention?

### ISSUE THREAD

**Issue by ipeacocks** [realpython/book3-exercises#25]
Hi.

As I can see part 3 was written for Python 2 and with older versions of pip packages than part 2 (I am talking about **django_ecommerce**). Also this repo is near 3-4 years old. So does this part worth the attention? Or better to invest time for some other Django book?

Thanks.

**Comment by mjhea0** [comment]
Depends on what your goals are.

1. If you're goal is to learn Python and Django then I highly recommend working through it. The majority of apps that you'd be working on out in the industry will be outdated. In fact, working with outdated tech is a sign that you are working for a company that had some success, as they would not have a legacy app otherwise. For example, in my day job I work with Angular 1.6, Flask, and Python 2.7. I would much rather be working with the latest and greatest versions, but the app I inherited happened to be using those versions. 

    Take the knowledge you learn in the first and second courses and apply it to the third course. Learning to code is less about tools and frameworks and languages and more about learning how to learn. Technologies come and go. If you can position yourself so that you can learn quickly then you will be able to adapt. 

    I can't think of a better way to prepare for a job then by learning the patterns in course 3 and then refactoring them yourself to the latest version! It's a complicated app with a number of moving pieces; it should help get you prepared.

1. On the other hand, if you are looking to get the knowledge you need to build a quick app and run a business then I would look elsewhere. In fact, I would steer away from Real Python in general since it's geared more for learning programming patterns and paradigms rather than getting an app up quick.

**Comment by ipeacocks** [comment]
Hi, @mjhea0. Thank you for comment.

I am devops. I like to learn something new. And first 2 books were absolutely awesome, they learned how to do work correct and efficient. Even more, I think that first book is absolutely must have for beginners: it studies how to code in a fun way, you can see the product of programming and it's **very important** for starters.

These 2 books are using almost latest software. Thats why I am asking you. 
For example now, only by experimental way, I've realised that code in book3 is for **python2** but there is no such info in book (or I am not attentive).

Ok, guys. I don't want to insult you, just confused.

**Comment by mjhea0** [comment]
About 3/4 of course 3 is Python 3. You will go through the process of upgrading from 2 to 3. 

Happy to help. Please email me (michael at realpython dot com) if you run into any issues or confusing parts. Once done, be sure to also check out https://testdriven.io/. Best!

**Comment by ipeacocks** [comment]
Now it is more clear. Thanks for supporting.

> Once done, be sure to also check out https://testdriven.io/.

Sure. I've seen it (and it looks promising) but don't have much time now. Maybe after 3rd book.

> Please email me (michael at realpython dot com) if you run into any issues or confusing parts.

Will do. Bye.

PS. You can close this issue.
